import { Platform, StyleSheet } from "react-native";
import { colors } from "../../shared/theme/colors";

export const S = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
    borderBottomWidth: 0
  },
  header: {
    padding: 16,
    alignItems: "center",
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  headerTitle: { fontSize: 18, fontWeight: "700", color: colors.textPrimary },
  badge: {
    backgroundColor: "rgba(1,138,190,0.08)",
    borderWidth: 0,
    borderColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 8,
  },
  badgeText: { color: colors.primary, fontWeight: "600" },
  totalBadge: {
    marginTop: 8,
    backgroundColor: "#e3f2fd",
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
  },
  totalBadgeText: { fontSize: 13, color: "#1565c0", fontWeight: "600" },
  nodeCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    shadowColor: "#000",
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  nodeText: { fontWeight: "700", fontSize: 20 },
  savingBadge: {
    backgroundColor: "#e8f5e9",
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "#a5d6a7",
    marginBottom: 4,
  },
  savingBadgeText: { fontSize: 10, color: "#2e7d32", fontWeight: "600" },
});

export const BS = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)" },
  kavWrapper: { position: "absolute", bottom: 0, left: 0, right: 0 },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingBottom: 40,
    paddingTop: 12,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 20,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: "#e0e0e0",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  dayLabel: { fontSize: 22, fontWeight: "700", color: colors.textPrimary },
  dateLabel: {
    fontSize: 13,
    color: "#888",
    marginTop: 4,
    marginBottom: 16,
    textTransform: "capitalize",
  },
  divider: { height: 1, backgroundColor: "#f0f0f0", marginBottom: 20 },
  inputLabel: { fontSize: 15, fontWeight: "600", color: "#333", marginBottom: 10 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f7f7f7",
    borderRadius: 14,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: "#e0e0e0",
  },
  input: {
    flex: 1,
    fontSize: 20,
    fontWeight: "700",
    color: "#1a1a2e",
    paddingVertical: 12,
  },
  currency: { fontSize: 18, fontWeight: "600", color: "#888", marginLeft: 6 },
  existingNote: { fontSize: 12, color: colors.success, marginTop: 8, marginLeft: 4 },
  btnRow: { flexDirection: "row", gap: 12, marginTop: 24 },
  btnCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: "#f0f0f0",
    alignItems: "center",
  },
  btnCancelText: { fontSize: 15, fontWeight: "600", color: "#666" },
  btnSave: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: "center",
  },
  btnSaveText: { fontSize: 15, fontWeight: "700", color: "#fff" },
});